version: "3.9"

services:
  builder:
    image: clojure:openjdk-19-tools-deps-slim-bullseye
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app

  graal:
    image: ghcr.io/graalvm/native-image:ol8-java17-22.2.0
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
